version: '3.9'
services:
    server:
        container_name: market-square-server
        restart: always
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        container_name: market-square-db
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: mysecretpassword
