spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/market-square-db
        username: postgres
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2MB
            max-file-size: 5MB
            max-request-size: 10MB

hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect

security:
    basic:
        enabled: false
cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY_ID}
            secret-key: ${AWS_SECRET_ACCESS_KEY}
        region:
            static: ${AWS_REGION}
        stack:
            auto: false
server:
    error:
        include-message: always
        include-binding-errors: always

bucket:
    name: market-square-storage
#    port: 9000

#application:
#    bucket:
#        name: market-square-storage
