server:
    error:
        include-message: always
        include-binding-errors: always
    port: 8001
spring:
    profiles:
        active: dev
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/market-square-db
        username: postgres
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
#        show-sql: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2MB
            max-file-size: 5MB
            max-request-size: 10MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect

security:
    basic:
        enabled: false
cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY_ID}
            secret-key: ${AWS_SECRET_ACCESS_KEY}
        region:
            static: ${AWS_REGION}
        stack:
            auto: false

bucket:
    name: market-sqaure-storage

jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

---

spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:postgresql://localhost:5432/market-square-db-prod
        username: postgres
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2MB
            max-file-size: 5MB
            max-request-size: 10MB

hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect

security:
    basic:
        enabled: false
cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY_ID}
            secret-key: ${AWS_SECRET_ACCESS_KEY}
        region:
            static: ${AWS_REGION}
        stack:
            auto: false

bucket:
    name: market-square-storage

---
#application:
#    bucket:
#        name: market-square-storage
